import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const captureHtml = await readFile(new URL('../capture/public/index.html', import.meta.url), 'utf8');
const replayHtml = await readFile(new URL('../capture/public/replay.html', import.meta.url), 'utf8');
const captureSource = await readFile(new URL('../capture/public/app.js', import.meta.url), 'utf8');
const replaySource = await readFile(new URL('../capture/public/replay.js', import.meta.url), 'utf8');

assert.match(captureHtml, /id="btn-start-capture"/);
assert.match(captureSource, /new MediaRecorder/);
assert.match(captureSource, /video-chunk/);
assert.match(captureSource, /finalize-video/);
assert.match(captureSource, /finalize-metadata/);
assert.match(captureSource, /connectPolarH10/);
assert.match(captureSource, /phase_start/);
assert.doesNotMatch(captureSource, /new RPPGPipeline/, 'capture acquisition should not run rPPG');

assert.match(replaySource, /from ['"]\/shared\/algorithm\/rppg-pipeline\.js['"]/);
assert.match(replaySource, /from ['"]\/shared\/algorithm\/roi-utils\.js['"]/);
assert.match(replaySource, /requestVideoFrameCallback|setTimeout/);
assert.match(replaySource, /addEventListener\('ended'/, 'replay should resolve and save when the video ended event fires');
assert.match(replaySource, /function capturePerfMsForVideoTime/, 'replay should map video time back to original capture perfMs');
assert.match(replaySource, /recordingStartedPerfMs/, 'replay should use capture recording start time for event alignment');
assert.match(replaySource, /polarSamples/, 'replay should load Polar samples for live chart and interval summaries');
assert.match(replaySource, /upperFacePipeline/, 'replay should run a second pipeline on the raw upper-face ROI');
assert.match(replaySource, /upperFaceRppgSamples/, 'replay should store upper-face rPPG estimates separately');
assert.match(replaySource, /foreheadOnlyPipeline/, 'replay should run a forehead-only regional pipeline');
assert.match(replaySource, /cheeksOnlyPipeline/, 'replay should run a cheeks-only regional pipeline');
assert.match(replaySource, /foreheadOnlyRppgSamples/, 'replay should store forehead-only estimates separately');
assert.match(replaySource, /cheeksOnlyRppgSamples/, 'replay should store cheeks-only estimates separately');
assert.match(replaySource, /foreheadCheekCwtBeats/, 'interval summary should include forehead+cheek CWT beats');
assert.match(replaySource, /foreheadCheekMadanPcaCwtBeats/, 'interval summary should include forehead+cheek Madan PCA CWT beats');
assert.match(replaySource, /foreheadCheekMadanPosCwtBeats/, 'interval summary should include forehead+cheek Madan POS CWT beats');
assert.match(replaySource, /foreheadOnlyCwtBeats/, 'interval summary should include forehead-only CWT beats');
assert.match(replaySource, /foreheadOnlyMadanPcaCwtBeats/, 'interval summary should include forehead-only Madan PCA CWT beats');
assert.match(replaySource, /cheeksOnlyCwtBeats/, 'interval summary should include cheeks-only CWT beats');
assert.match(replaySource, /cheeksOnlyMadanPosCwtBeats/, 'interval summary should include cheeks-only Madan POS CWT beats');
assert.match(replaySource, /upperFaceCwtBeats/, 'interval summary should include upper-face CWT beats');
assert.match(replaySource, /upperFaceLsBeats/, 'interval summary should include upper-face LS beats');
assert.match(replaySource, /cwtGatedBpm/, 'replay should persist gated CWT samples');
assert.doesNotMatch(replaySource, /cwtGatedBeats|CwtGatedBeats/, 'interval summary should not include gated CWT beats');
assert.match(replaySource, /\/api\/capture\/sessions/, 'replay should list all existing capture sessions');
assert.match(replayHtml, /id="btn-run-all-sessions"/, 'replay page should run all sessions without manual entry');
assert.doesNotMatch(replayHtml, /id="roi-mode"/, 'replay should not expose compact ROI controls');
assert.doesNotMatch(replayHtml, /id="roi-composition"/, 'replay should not expose ROI composition controls');
assert.doesNotMatch(replayHtml, /id="target-fs"/, 'replay should not expose downsampling controls');
assert.doesNotMatch(replaySource, /landmarkPatchV2/, 'active replay code should not reference oversized landmarkPatchV2');
assert.doesNotMatch(replaySource, /LANDMARK_PATCH_COMPACT|compact_all|compact_cheeks|compact_forehead/, 'replay should not run compact ROI variants');
assert.doesNotMatch(replaySource, /SOFT_YCBCR|softYcbcr/, 'replay should not run soft skin variants');
assert.doesNotMatch(replaySource, /15fps|12fps|target-fs/, 'replay should not run downsample variants');
assert.match(replaySource, /targetFs:\s*30/, 'replay should use a fixed 30 FPS pipeline');
assert.match(replaySource, /fixedSampleCount/, 'replay should persist fixed sampling diagnostics');
assert.match(replaySource, /interEyeDeltaPct/, 'replay should persist depth-motion diagnostics');
assert.match(replaySource, /scaleJump/, 'replay should persist scale-jump diagnostics');
assert.match(replaySource, /roiRegionSet:\s*'upperFace'/, 'upper-face pipeline samples should be labeled by ROI source');
assert.match(replayHtml, /id="hr-chart"/, 'replay page should show a live HR chart');
assert.match(replayHtml, /Polar[\s\S]*CWT Raw[\s\S]*CWT Gated[\s\S]*LS/, 'replay page should label Polar, raw CWT, gated CWT, and LS');
assert.match(replaySource, /\/api\/capture\/session\/.+\/replay/);
