import { mkdir, writeFile, appendFile, access } from 'node:fs/promises';
import path from 'node:path';
import { appendCsvLine, toCsv } from './csv.js';
import {
  flattenSimplifiedParticipantSummary,
  summarizeSimplifiedSession
} from './simplified-analysis.js';
import { readJsonBody } from './http.js';

const SUMMARY_COLUMNS = [
  'session_id',
  'participant_id',
  'created_at',
  'language',
  'workflow',
  'polar_connected',
  'interval_count',
  'total_cwt_polar_beats',
  'total_cwt_rppg_beats',
  'total_cwt_signed_error',
  'total_cwt_absolute_error',
  'total_cwt_percent_error',
  'total_cwt_alignment_index',
  'total_cwt_inconsistency_index',
  'total_ls_polar_beats',
  'total_ls_rppg_beats',
  'total_ls_signed_error',
  'total_ls_absolute_error',
  'total_ls_percent_error',
  'total_ls_alignment_index',
  'total_ls_inconsistency_index',
  'total_madan_pca_cwt_polar_beats',
  'total_madan_pca_cwt_rppg_beats',
  'total_madan_pca_cwt_signed_error',
  'total_madan_pca_cwt_absolute_error',
  'total_madan_pca_cwt_percent_error',
  'total_madan_pca_cwt_alignment_index',
  'total_madan_pca_cwt_inconsistency_index',
  'total_madan_pos_cwt_polar_beats',
  'total_madan_pos_cwt_rppg_beats',
  'total_madan_pos_cwt_signed_error',
  'total_madan_pos_cwt_absolute_error',
  'total_madan_pos_cwt_percent_error',
  'total_madan_pos_cwt_alignment_index',
  'total_madan_pos_cwt_inconsistency_index',
  'baseline_cwt_polar_beats',
  'baseline_cwt_rppg_beats',
  'baseline_cwt_signed_error',
  'baseline_cwt_absolute_error',
  'baseline_cwt_percent_error',
  'baseline_cwt_alignment_index',
  'baseline_cwt_inconsistency_index',
  'baseline_ls_polar_beats',
  'baseline_ls_rppg_beats',
  'baseline_ls_signed_error',
  'baseline_ls_absolute_error',
  'baseline_ls_percent_error',
  'baseline_ls_alignment_index',
  'baseline_ls_inconsistency_index',
  'baseline_madan_pca_cwt_polar_beats',
  'baseline_madan_pca_cwt_rppg_beats',
  'baseline_madan_pca_cwt_signed_error',
  'baseline_madan_pca_cwt_absolute_error',
  'baseline_madan_pca_cwt_percent_error',
  'baseline_madan_pca_cwt_alignment_index',
  'baseline_madan_pca_cwt_inconsistency_index',
  'baseline_madan_pos_cwt_polar_beats',
  'baseline_madan_pos_cwt_rppg_beats',
  'baseline_madan_pos_cwt_signed_error',
  'baseline_madan_pos_cwt_absolute_error',
  'baseline_madan_pos_cwt_percent_error',
  'baseline_madan_pos_cwt_alignment_index',
  'baseline_madan_pos_cwt_inconsistency_index',
  'recovery_cwt_polar_beats',
  'recovery_cwt_rppg_beats',
  'recovery_cwt_signed_error',
  'recovery_cwt_absolute_error',
  'recovery_cwt_percent_error',
  'recovery_cwt_alignment_index',
  'recovery_cwt_inconsistency_index',
  'recovery_ls_polar_beats',
  'recovery_ls_rppg_beats',
  'recovery_ls_signed_error',
  'recovery_ls_absolute_error',
  'recovery_ls_percent_error',
  'recovery_ls_alignment_index',
  'recovery_ls_inconsistency_index',
  'recovery_madan_pca_cwt_polar_beats',
  'recovery_madan_pca_cwt_rppg_beats',
  'recovery_madan_pca_cwt_signed_error',
  'recovery_madan_pca_cwt_absolute_error',
  'recovery_madan_pca_cwt_percent_error',
  'recovery_madan_pca_cwt_alignment_index',
  'recovery_madan_pca_cwt_inconsistency_index',
  'recovery_madan_pos_cwt_polar_beats',
  'recovery_madan_pos_cwt_rppg_beats',
  'recovery_madan_pos_cwt_signed_error',
  'recovery_madan_pos_cwt_absolute_error',
  'recovery_madan_pos_cwt_percent_error',
  'recovery_madan_pos_cwt_alignment_index',
  'recovery_madan_pos_cwt_inconsistency_index',
  'total_cwt_hr_n_seconds',
  'total_cwt_hr_mae',
  'total_cwt_hr_rmse',
  'total_cwt_hr_bias',
  'total_cwt_hr_mape',
  'total_cwt_hr_pearson_r',
  'total_cwt_hr_lin_ccc',
  'total_ls_hr_n_seconds',
  'total_ls_hr_mae',
  'total_ls_hr_rmse',
  'total_ls_hr_bias',
  'total_ls_hr_mape',
  'total_ls_hr_pearson_r',
  'total_ls_hr_lin_ccc',
  'baseline_cwt_hr_n_seconds',
  'baseline_cwt_hr_mae',
  'baseline_cwt_hr_rmse',
  'baseline_cwt_hr_bias',
  'baseline_cwt_hr_mape',
  'baseline_cwt_hr_pearson_r',
  'baseline_cwt_hr_lin_ccc',
  'baseline_ls_hr_n_seconds',
  'baseline_ls_hr_mae',
  'baseline_ls_hr_rmse',
  'baseline_ls_hr_bias',
  'baseline_ls_hr_mape',
  'baseline_ls_hr_pearson_r',
  'baseline_ls_hr_lin_ccc',
  'recovery_cwt_hr_n_seconds',
  'recovery_cwt_hr_mae',
  'recovery_cwt_hr_rmse',
  'recovery_cwt_hr_bias',
  'recovery_cwt_hr_mape',
  'recovery_cwt_hr_pearson_r',
  'recovery_cwt_hr_lin_ccc',
  'recovery_ls_hr_n_seconds',
  'recovery_ls_hr_mae',
  'recovery_ls_hr_rmse',
  'recovery_ls_hr_bias',
  'recovery_ls_hr_mape',
  'recovery_ls_hr_pearson_r',
  'recovery_ls_hr_lin_ccc',
  'interval_metrics_json',
  'beat_count_indices_json',
  'phase_metrics_json'
];

export async function createSimplifiedSession(dataRoot, { participantId, language }) {
  await mkdir(dataRoot, { recursive: true });
  const createdAt = new Date().toISOString();
  const sessionId = `${safeId(participantId)}_${createdAt.replace(/[:.]/g, '-')}`;
  const sessionDir = path.join(dataRoot, 'sessions', sessionId);
  await mkdir(sessionDir, { recursive: true });
  const manifest = {
    sessionId,
    participantId,
    language,
    createdAt,
    workflow: 'simplified'
  };
  await writeJson(path.join(sessionDir, 'session.json'), manifest);
  return { ...manifest, sessionDir };
}

export async function finalizeSimplifiedSession(dataRoot, session) {
  const sessionDir = path.join(dataRoot, 'sessions', session.sessionId);
  await mkdir(sessionDir, { recursive: true });
  const normalized = normalizeSimplifiedSession(session);
  const summary = summarizeSimplifiedSession(normalized);
  const participantRow = flattenSimplifiedParticipantSummary(summary);

  await writeJson(path.join(sessionDir, 'session.json'), {
    ...normalized,
    summary
  });
  await writeFile(path.join(sessionDir, 'polar_hr_1hz.csv'), toCsv(normalized.polarSamples, [
    'sessionId',
    'participantId',
    'wallTime',
    'perfMs',
    'hrBpm',
    'rrMsJson'
  ]));
  await writeFile(path.join(sessionDir, 'rppg_hr_1hz.csv'), toCsv(normalized.rppgSamples, [
    'sessionId',
    'participantId',
    'wallTime',
    'perfMs',
    'phase',
    'cwtBpm',
    'lsBpm',
    'cwtRawBpm',
    'cwtConstrainedBpm',
    'cwtSmoothedBpm',
    'cwtGatedBpm',
    'cwtAccepted',
    'cwtRawAccepted',
    'cwtGatedAccepted',
    'cwtQuality',
    'cwtRejectReason',
    'cwtFallbackReason',
    'cwtPowerRatio',
    'cwtLsDivergenceBpm',
    'cwtJumpBpm',
    'cwtCoverageRatio',
    'cwtDeltaBpm',
    'cwtSearchLowBpm',
    'cwtSearchHighBpm',
    'targetFs',
    'effectiveFrameRate',
    'frameGapCount',
    'downsampleMode',
    'antiAliasWindowMs',
    'roiMode',
    'roiComposition',
    'skinMode',
    'interEyeDeltaPct',
    'interEyeVelocityPctPerSec',
    'patchAreaDeltaPct',
    'scaleJump'
  ]));
  await writeFile(path.join(sessionDir, 'rppg_debug.csv'), toCsv(normalized.rppgDebugSamples, [
    'sessionId',
    'participantId',
    'wallTime',
    'perfMs',
    'debugType',
    'phase',
    'intervalId',
    'cwtBpm',
    'lsBpm',
    'cwtRawBpm',
    'cwtConstrainedBpm',
    'cwtSmoothedBpm',
    'cwtGatedBpm',
    'cwtAccepted',
    'cwtRawAccepted',
    'cwtGatedAccepted',
    'cwtQuality',
    'cwtRejectReason',
    'cwtFallbackReason',
    'cwtPowerRatio',
    'cwtLsDivergenceBpm',
    'cwtJumpBpm',
    'cwtCoverageRatio',
    'cwtDeltaBpm',
    'cwtSearchLowBpm',
    'cwtSearchHighBpm',
    'roiR',
    'roiG',
    'roiB',
    'roiRegionSet',
    'roiMotionPx',
    'rgbJump',
    'faceRollDeg',
    'interEyeDistancePx',
    'interEyeDeltaPct',
    'interEyeVelocityPctPerSec',
    'patchAreaPx',
    'patchAreaDeltaPct',
    'fixedSampleCount',
    'effectiveSkinSampleCount',
    'scaleJump',
    'roiComposition',
    'roiSkinFraction',
    'cwtWindowSamples',
    'cwtWindowSec',
    'cwtBestPower',
    'cwtSecondBpm',
    'cwtSecondPower',
    'cwtPowerRatio',
    'cwtSignalMedian',
    'cwtSignalMad',
    'cwtSignalScale',
    'cwtSignalMaxAbsZ',
    'signalClippedFraction',
    'cwtCountRawPeaks',
    'cwtCountValidPeaks',
    'cwtTopCandidatesJson'
  ]));
  await writeFile(path.join(sessionDir, 'rppg_raw_signal.csv'), toCsv(normalized.rppgRawSamples, [
    'sessionId',
    'participantId',
    'wallTime',
    'perfMs',
    'debugType',
    'phase',
    'rawR',
    'rawG',
    'rawB',
    'frameDeltaMs',
    'roiX',
    'roiY',
    'roiWidth',
    'roiHeight',
    'roiMode',
    'roiComposition',
    'skinMode',
    'skinPixelCount',
    'hardSkinPixelCount',
    'effectiveSkinPixelCount',
    'sampledPixelCount',
    'skinFraction',
    'hardSkinFraction',
    'effectiveSkinFraction',
    'rgbJump',
    'faceRollDeg',
    'interEyeDistancePx',
    'interEyeDeltaPct',
    'interEyeVelocityPctPerSec',
    'patchAreaPx',
    'patchAreaDeltaPct',
    'fixedSampleCount',
    'effectiveSkinSampleCount',
    'scaleJump',
    'roiMotionPx',
    'roiRegionSet',
    'roiCandidateCount',
    'callbackPerfMs',
    'resampledR',
    'resampledG',
    'resampledB',
    'filteredR',
    'filteredG',
    'filteredB',
    'meanR',
    'meanG',
    'meanB',
    'alpha',
    'posValue',
    'posBufferLength'
  ]));
  await writeFile(path.join(sessionDir, 'rppg_roi_candidates.csv'), toCsv(normalized.rppgRoiCandidates, [
    'sessionId',
    'participantId',
    'wallTime',
    'perfMs',
    'phase',
    'roiName',
    'roiX',
    'roiY',
    'roiWidth',
    'roiHeight',
    'roiMode',
    'roiComposition',
    'skinMode',
    'roiCenterX',
    'roiCenterY',
    'roiMotionPx',
    'rgbJump',
    'faceRollDeg',
    'interEyeDistancePx',
    'interEyeDeltaPct',
    'interEyeVelocityPctPerSec',
    'patchAreaPx',
    'patchAreaDeltaPct',
    'fixedSampleCount',
    'effectiveSkinSampleCount',
    'scaleJump',
    'polygonJson',
    'normalizedPolygonJson',
    'skinPixelCount',
    'hardSkinPixelCount',
    'effectiveSkinPixelCount',
    'sampledPixelCount',
    'skinFraction',
    'hardSkinFraction',
    'effectiveSkinFraction',
    'skinFractionDelta',
    'accepted',
    'rejectReason',
    'roiR',
    'roiG',
    'roiB'
  ]));
  await writeFile(path.join(sessionDir, 'rppg_signal_quality.csv'), toCsv(normalized.rppgSignalQualitySamples, [
    'sessionId',
    'participantId',
    'wallTime',
    'perfMs',
    'phase',
    'roiRegionSet',
    'roiSkinFraction',
    'hardSkinFraction',
    'effectiveSkinPixelCount',
    'effectiveSkinSampleCount',
    'fixedSampleCount',
    'roiMotionPx',
    'rgbJump',
    'faceRollDeg',
    'interEyeDistancePx',
    'interEyeDeltaPct',
    'interEyeVelocityPctPerSec',
    'patchAreaPx',
    'patchAreaDeltaPct',
    'scaleJump',
    'roiComposition',
    'frameDeltaMs',
    'effectiveFrameRate',
    'frameGapCount',
    'targetFs',
    'downsampleMode',
    'antiAliasWindowMs',
    'posValue',
    'posBufferLength',
    'cwtLsDivergenceBpm',
    'cwtAccepted',
    'cwtRawAccepted',
    'cwtGatedAccepted',
    'cwtQuality',
    'cwtRejectReason',
    'cwtFallbackReason',
    'signalScale',
    'signalClippedFraction'
  ]));
  await writeFile(path.join(sessionDir, 'cwt_power_diagnostics.csv'), toCsv(normalized.cwtPowerDiagnostics, [
    'sessionId',
    'participantId',
    'wallTime',
    'perfMs',
    'phase',
    'cwtRawBpm',
    'cwtConstrainedBpm',
    'cwtGatedBpm',
    'cwtSmoothedBpm',
    'cwtAccepted',
    'cwtRawAccepted',
    'cwtGatedAccepted',
    'cwtQuality',
    'cwtRejectReason',
    'cwtFallbackReason',
    'cwtLsDivergenceBpm',
    'cwtJumpBpm',
    'cwtCoverageRatio',
    'cwtPowerRatio',
    'cwtBestPower',
    'cwtSecondBpm',
    'cwtSecondPower',
    'cwtSearchLowBpm',
    'cwtSearchHighBpm',
    'cwtTopCandidatesJson'
  ]));
  await writeFile(path.join(sessionDir, 'events.csv'), toCsv(normalized.events, [
    'sessionId',
    'participantId',
    'wallTime',
    'perfMs',
    'eventType',
    'phase',
    'intervalId',
    'payloadJson'
  ]));
  await writeFile(path.join(sessionDir, 'interval_summary.csv'), toCsv(summary.intervalSummaries));
  await appendParticipantSummary(dataRoot, participantRow);
  return summary;
}

function normalizeSimplifiedSession(session) {
  const stamp = (row) => ({
    sessionId: session.sessionId,
    participantId: session.participantId,
    ...row
  });
  return {
    ...session,
    workflow: 'simplified',
    polarSamples: (session.polarSamples ?? []).map((sample) => ({
      ...stamp(sample),
      rrMsJson: sample.rrMsJson ?? JSON.stringify(sample.rrIntervalsMs ?? [])
    })),
    rppgSamples: (session.rppgSamples ?? []).map(stamp),
    rppgDebugSamples: (session.rppgDebugSamples ?? []).map(stamp),
    rppgRawSamples: (session.rppgRawSamples ?? []).map(stamp),
    rppgRoiCandidates: (session.rppgRoiCandidates ?? []).map(stamp),
    rppgSignalQualitySamples: (session.rppgSignalQualitySamples ?? []).map(stamp),
    cwtPowerDiagnostics: (session.cwtPowerDiagnostics ?? []).map(stamp),
    events: (session.events ?? []).map((event) => ({
      ...stamp(event),
      payloadJson: event.payloadJson ?? JSON.stringify(event.payload ?? {})
    })),
    intervals: session.intervals ?? []
  };
}

async function appendParticipantSummary(dataRoot, row) {
  const summaryPath = path.join(dataRoot, 'participants_summary.csv');
  try {
    await access(summaryPath);
  } catch {
    await writeFile(summaryPath, `${SUMMARY_COLUMNS.join(',')}\n`);
  }
  await appendFile(summaryPath, appendCsvLine(row, SUMMARY_COLUMNS));
}

async function writeJson(filePath, value) {
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function safeId(value) {
  return String(value || 'participant')
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .slice(0, 80);
}

export { readJsonBody };
